Revert "SimSettings: Handle NoClassDefFoundError on devices without telephony-ext"
This reverts commit a5f0e8a79751468556209ee13539a0e4a7202c3e.

Signed-off-by: YumeMichi <do4suki@gmail.com>